name: CI
on:
   # События, которые запускают jobs
    push:
      branches: [ "spbu" ]
    pull_request:
      branches: [ "spbu" ]

#permissions:
#  contents: write

jobs: # jobs запускаются параллельно, если не указана последовательность
  deploy: # Название job вы можете назвать как угодно
    runs-on: ubuntu-22.04 # Операционная система в виртуальной машине, в которой запускаются процессы
#    concurrency:
#      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Git checkout # Actions от github: проверяет репозиторий, гит и т.д.
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

#      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
#        run: git submodule update --init --recursive


      - name: 📄 Generate pdf_lastmod.yaml
        run: |
          mkdir -p data
          echo "pdf_lastmod:" > data/pdf_lastmod.yaml
          for f in static/**/*.pdf; do
            filename=$(basename "$f")
            filedate=$(git log -1 --format="%ad" --date=short -- "$f")
            echo "  $filename: \"$filedate\"" >> data/pdf_lastmod.yaml
          done
          cat data/pdf_lastmod.yaml
          ls -R data

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.135.0'
          extended: true

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.MYSITE_TOKEN }}
          publish_dir: ./public

      - name: 📂 Sync Files
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          remote_host: lubkov.spbu.ru
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.REM_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_path: ${{ secrets.DEST_PATH }}
          path: ./public/

      - name: 📄 Upload lastmod.yaml separately
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr
          remote_host: lubkov.spbu.ru
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.REM_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
          remote_path: ${{ secrets.DEST_PATH }}/data
          path: ./data/

#       website on spbu hosting
#      - name: Set up WireGuard Connection
#        uses: niklaskeerl/easy-wireguard-action@v2
#        with:
#          WG_CONFIG_FILE: ${{ secrets.WG_CONFIG_FILE_SPEEDSTER }}

#      - name: 📂 Sync files
#        uses: SamKirkland/FTP-Deploy-Action@4.3.2
#        with:
#          server: ${{ secrets.LINK_FTP_SPBU }}
#          username: ${{ secrets.USERNAME_FPT_SPBU }}
#          password: ${{ secrets.PASS_FTP_SPBU }}
#          local-dir: ./public/


         